### PR TITLE
model type validations

### PR DESCRIPTION
**Pull request by mmmmaximus**
## Description of work

Added model type validations 

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Chore (Minor requested change)

## Checklist

- [x] I have added tests to prove my feature is functional
- [x] My code is sufficiently documented, include sample of how to use the component

### CODE REVIEW

**Comment by benrobinson-ms** [comment]
Does the truck need anything added to it so it can specify what its model type is?

**Review by benrobinson-ms — APPROVED** [review]
Looks fine, just check if a truck can ask for its model_type

**Comment by mmmmaximus** [comment]
> Does the truck need anything added to it so it can specify what its model type is?

I think the truck would require extra validation for presence of model type? im not too sure

**Comment by benrobinson-ms** [comment]
does it need something like `belongs_to :model_type`?

**Comment by mmmmaximus** [comment]
I guess so. So that means that for every has_many, there will be a belongs_to somewhere else?

**Comment by benrobinson-ms** [comment]
not guaranteed, but generally yeah.
we can go over this a little more this afternoon

**Pull request merged**
